import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar.js'
import Footer from '../components/Footer.js'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CEDOC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
        
      </Navbar>

      <Footer className={styles.footer} >
        
      </Footer>
    </div>
  )
}