import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar/Navbar.js';
import Footer from '../components/footer/Footer.js';
import Banner from '../components/banner/Banner.js';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CEDOC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cedoc.ico" />
        <link href="http://fonts.cdnfonts.com/css/butler" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500;700&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar>      
      </Navbar>
      <Banner>
      </Banner>
      <div className={styles.searchCenter}>
        <input className={styles.searchPlaceholder} type="search" id="site-search"/> 
        <button className={styles.buttonSearch}><FontAwesomeIcon icon="fa-solid fa-magnifying-glass" width={30}/></button>
      </div>
      <div className={styles.resumenGrid}>
        <div className={styles.resumenGridItem}>+3400 <br/> articulos</div>
        <div className={styles.resumenGridItem}>+3500<br/>e-books</div>
        <div className={styles.resumenGridItem}>+5400<br/>fotografías</div>
      </div>
      <div className={styles.gridIndex}>
        <div className={styles.gridItem}><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/01.png"  />
          <div className={styles.textGrid}> Conoce la agenda de actividades</div>
          <button className={styles.readMore}> Leer más </button>
        </div>
        <div className={styles.gridItem}>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/02.png" />
            <button className={styles.readMore}> Leer más </button>
          </div>
        <div className={styles.gridItem}>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/03.png" />
            <button className={styles.readMore}> Leer más </button>
          </div>
        <div className={styles.gridItem}>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/04.png" />
            <button className={styles.readMore}> Leer más </button>
          </div>
        <div className={styles.gridItem}>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/05.png" />
            <button className={styles.readMore}> Leer más </button>
          </div>
        <div className={styles.gridItem}>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76301/06.png" />
            <button className={styles.readMore}> Leer más </button>
          </div>
      </div>
      <Footer >
      </Footer>
    </div>
  )
}

